### PR TITLE
TTL Snapshot Bug Fixes

### LINKED ISSUE #70: TTL KV's are lost during RocksDB/Badger Snapshot/Backup/Restore
- TTL CF completely skipped in GetSnapshot for rocksdb
- TTL Meta lost in Badger GetSnapshot

### PR DESCRIPTION
**Pull request by kingster**
Fixes #70

- [x] Rocksdb fixes
- [x] Badger fixes
- [x] dkvReplStore.Put
- [x] Streaming Archieve https://github.com/flipkart-incubator/dkv/pull/80

### CODE REVIEW

File: cmd/dkvsrv/main.go [hunk 1]
```diff
@@ -345,13 +345,14 @@ func newKVStore() (storage.KVStore, storage.ChangePropagator, storage.ChangeAppl
 
 	dataDir := path.Join(dbFolder, "data")
 	slg.Infof("Using %s as data directory", dataDir)
+
+	sstDir := path.Join(dbFolder, "sst")
```
Comment (KalyanAkella) [inline cmd/dkvsrv/main.go:349]: Isn't the data folder already holding the SST files. Rather, why do we need this ?

File: internal/storage/badger/store.go [hunk 2]
```diff
@@ -271,38 +282,64 @@ func (bdb *badgerDB) CompareAndSet(key, expect, update []byte) (bool, error) {
...
 		return nil, err
 	}
 
-	var buf bytes.Buffer
-	err := gob.NewEncoder(&buf).Encode(snap)
-	return buf.Bytes(), err
+	w.Flush()
+	sstFile.Close()
+
+	return ioutil.ReadFile(sstFile.Name())
```
Comment (KalyanAkella) [inline internal/storage/badger/store.go:319]: Given that eventually all the contents of `sstFile` need to be read into memory, why can't we just use `bytes.Buffer` which implements `io.Writer` at the beginning ?

File: internal/storage/rocksdb/store.go [hunk 3]
```diff
@@ -342,34 +343,30 @@ func (rdb *rocksDB) CompareAndSet(key, expect, update []byte) (bool, error) {
...
+	var fileName string
 	envOpts := gorocksdb.NewDefaultEnvOptions()
 	opts := gorocksdb.NewDefaultOptions()
 	sstWrtr := gorocksdb.NewSSTFileWriter(envOpts, opts)
 	defer sstWrtr.Destroy()
 
-	sstFile, err := storage.CreateTempFile(rdb.opts.sstDirectory, tempFilePrefix)
-	if err != nil {
-		return nil, err
+	if fileName = sstDir + "/default.cf"; cf == rdb.ttlCF {
```
Comment (KalyanAkella) [inline internal/storage/rocksdb/store.go:355]: Check if this hard-coding can be removed in preference for temp file (like the Badger impl.) based approach.

**Review by KalyanAkella — CHANGES_REQUESTED** [review]
We should explore if the ZIP archival can be avoided and check if there's a simpler means to doing multi-CF snapshotting.

File: cmd/dkvsrv/main.go (hunk 1 above)
Comment (kingster) [reply cmd/dkvsrv/main.go:349]: This is required for snapshot creation. Earlier this was passed in L350-354, which is now moved up, so that the value can be reused for both rocksdb & badger.

File: internal/storage/badger/store.go (hunk 2 above)
Comment (kingster) [reply internal/storage/badger/store.go:319]: I want to change `GetSnapshot` & `PutSnapshot` to use streaming io (from file) hence, the entire functions are written in streaming fashion, except this last line, which loads up the entire file in-memory. Once the snapshot side-car streaming changes are in place, this functions would return the `file` reference, which would just mean changing this line to return just the `sstFile`

**Review by kingster — COMMENTED** [review]
> We should explore if the ZIP archival can be avoided and check if there's a simpler means to doing multi-CF snapshotting.

Yup, I am open to suggestions, this is the best I could think of based on the current available options.

File: internal/storage/rocksdb/store.go (hunk 3 above)
Comment (kingster) [reply internal/storage/rocksdb/store.go]: default.cf & ttl.cf are two named files which are generated inside the tmp directory which is created during the rocksdb snapshot process. Have removed from hard-coding and moved to constants. If we are able to have a single snapshot file for multi-CF then, we can get rid of these.

**Review by KalyanAkella — APPROVED** [review]
